//! Presse-papiers général, pour le repli copier/coller.
//!
//! Règles tenues ici :
//! - on photographie tout le contenu (chaque élément, chaque format) avant d'y
//!   toucher, et on le remet ensuite ;
//! - on ne remet la photo que si personne n'a copié entre-temps : le
//!   `changeCount` doit être encore celui de notre propre écriture ;
//! - nos écritures sont marquées « transitoires » pour que les gestionnaires
//!   d'historique du presse-papiers les ignorent.
//!
//! Le presse-papiers n'est jamais surveillé : on ne le lit qu'au moment d'une
//! opération déclenchée par le raccourci.

use objc2::rc::{autoreleasepool, Retained};
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardTypeString, NSPasteboardWriting};
use objc2_foundation::{NSArray, NSData, NSString};

/// Conventions de nspasteboard.org, respectées par Maccy, Raycast, Alfred,
/// Paste… : « ne pas enregistrer dans l'historique ».
const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// Au-delà, la photo n'est pas prise : on ne recopie pas en mémoire une vidéo
/// copiée dans le Finder. Le contenu n'est alors pas restauré, et c'est dit.
const SNAPSHOT_LIMIT_BYTES: usize = 64 * 1024 * 1024;

/// Contenu complet du presse-papiers à un instant donné.
#[derive(Default)]
pub struct Snapshot {
    items: Vec<Vec<(String, Vec<u8>)>>,
    /// Faux si la photo a été abandonnée (contenu trop volumineux).
    pub complete: bool,
}

fn general() -> Retained<NSPasteboard> {
    NSPasteboard::generalPasteboard()
}

pub fn change_count() -> isize {
    autoreleasepool(|_| general().changeCount())
}

pub fn snapshot() -> Snapshot {
    autoreleasepool(|_| {
        let pasteboard = general();
        let Some(items) = pasteboard.pasteboardItems() else {
            return Snapshot { items: Vec::new(), complete: true };
        };
        let mut total = 0usize;
        let mut saved = Vec::with_capacity(items.count());
        for item in items.iter() {
            let mut formats = Vec::new();
            for kind in item.types().iter() {
                if let Some(data) = item.dataForType(&kind) {
                    let bytes = data.to_vec();
                    total += bytes.len();
                    if total > SNAPSHOT_LIMIT_BYTES {
                        return Snapshot { items: Vec::new(), complete: false };
                    }
                    formats.push((kind.to_string(), bytes));
                }
            }
            saved.push(formats);
        }
        Snapshot { items: saved, complete: true }
    })
}

/// Remet une photo. Renvoie le nouveau `changeCount`.
pub fn restore(snapshot: &Snapshot) -> isize {
    autoreleasepool(|_| {
        let pasteboard = general();
        pasteboard.clearContents();
        let items: Vec<Retained<ProtocolObject<dyn NSPasteboardWriting>>> = snapshot
            .items
            .iter()
            .map(|formats| {
                let item = NSPasteboardItem::new();
                for (kind, bytes) in formats {
                    let data = NSData::with_bytes(bytes);
                    item.setData_forType(&data, &NSString::from_str(kind));
                }
                ProtocolObject::from_retained(item)
            })
            .collect();
        if !items.is_empty() {
            pasteboard.writeObjects(&NSArray::from_retained_slice(&items));
        }
        pasteboard.changeCount()
    })
}

/// Écrit du texte brut, marqué transitoire. Renvoie le nouveau `changeCount`.
pub fn write_transient_text(text: &str) -> isize {
    write_text(text, true)
}

/// Écrit du texte brut à la demande explicite de l'utilisateur (« Copier »).
pub fn write_user_text(text: &str) -> isize {
    write_text(text, false)
}

fn write_text(text: &str, transient: bool) -> isize {
    autoreleasepool(|_| {
        let pasteboard = general();
        pasteboard.clearContents();
        let item = NSPasteboardItem::new();
        // SAFETY : constante exportée par AppKit.
        let string_type = unsafe { NSPasteboardTypeString };
        item.setString_forType(&NSString::from_str(text), string_type);
        if transient {
            let empty = NSData::new();
            item.setData_forType(&empty, &NSString::from_str(TRANSIENT_TYPE));
            item.setData_forType(&empty, &NSString::from_str(AUTO_GENERATED_TYPE));
        }
        let items = [ProtocolObject::from_retained(item)];
        pasteboard.writeObjects(&NSArray::from_retained_slice(&items));
        pasteboard.changeCount()
    })
}

pub fn read_text() -> Option<String> {
    autoreleasepool(|_| {
        // SAFETY : constante exportée par AppKit.
        let string_type = unsafe { NSPasteboardTypeString };
        general().stringForType(string_type).map(|text| text.to_string())
    })
}

/// VS Code (et les éditeurs Monaco) copient la ligne entière quand rien n'est
/// sélectionné, et le signalent dans un format privé. Ce n'est pas une
/// sélection : la traiter ferait coller une ligne réécrite au lieu de
/// remplacer.
pub fn is_empty_selection_copy() -> bool {
    autoreleasepool(|_| {
        let data = general().stringForType(&NSString::from_str("vscode-editor-data"));
        data.is_some_and(|json| {
            let json = json.to_string();
            json.contains("\"isFromEmptySelection\":true")
        })
    })
}
